#!/bin/bash

### BEGIN INIT INFO
# Provides:          scriptname
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

#PROGRAM_HOME домашняя директория программы (для запуска\остановки)
export PROGRAM_HOME=/home/Buldozer/reddit
cd ${PROGRAM_HOME}
puma -d
