#!/bin/bash

### BEGIN INIT INFO
# Provides:          scriptname
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

#PROGRAM_HOME домашняя директория программы (для запуска\остановки)
export PROGRAM_HOME=/home/Buldozer/reddit
program_pid() {
    echo $(ps aux | grep puma | grep -v grep | tr -s " "|cut -d" " -f2)
}
start() {
    pid=$(program_pid)
    if [ -n "$pid" ]
        then
        echo -e "\e[00;31mProgram is already running (pid: $pid)\e[00m"
    else
        echo -e "\e[00;32mStarting Program\e[00m"
        cd ${PROGRAM_HOME}
        puma -d
        status
  fi
  return 0
}
